spring:
  profiles:
    include: devse
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8004

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
