spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dliot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8091

mqtt:
  inbound:
    url: tcp://127.0.0.1:8031
    username: admin
    password: 1832079HH1832080
    clientId: iotPublisheraa
    topics: records
  outbound:
    urls: tcp://127.0.0.1:8031
    username: admin
    password: 1832079HH1832080
    clientId: iotConsumeraa
    topic: records

