spring:
  profiles:
    active: dev

mqtt:
  inbound:
    url: tcp://127.0.0.1:61613
    username: admin
    password: password
    clientId: iotPublisher
    topics: iot
  outbound:
    urls: tcp://127.0.0.1:61613
    username: admin
    password: password
    clientId: iotConsumer
    topic: iot

